default:
  collection: transmississippi
  collection_desc: "Trans-Mississippi and International Exposition"
  solr_core: nonapi_transmississippi
  tei_solr_xsl: scripts/nonapi_transmiss2solr.xsl
  variables_solr:
    slug: transmississippi

  # transmississippi CSVs are not in utf-8
  csv_encoding: "iso-8859-1"

